### ISSUE TITLE
missing argument for round numbers in certain context

### ISSUE THREAD

**Issue by MatthieuTricottet** [AndrewChap/num2tex#2]
When using num2tex(x,precision=p), it yields "\times 10^n", omitting the "1", for any
x = 10^n with p <= n+1. It does produce the expected result for a.10^n if a <> 1, though.

**Comment by Astrokiwi** [comment]
I encountered this issue myself. I've fixed it, added in a test case, and made a pull request

**Comment by thedoctar** [comment]
I just downloaded num2tex and am having this issue. When will this be fixed?

**Comment by AndrewChap** [comment]
Apologies for the delay, I've accepted @Astrokiwi's [pull request](https://github.com/AndrewChap/num2tex/pull/3).  Thank you @Astrokiwi for the fix!
